apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: devops-tools
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    path: ./external-secrets/external-secrets
    repoURL: https://github.com/msdeleyto/homelab-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
        istio.io/dataplane-mode: ambient
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
