apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media
  namespace: devops-tools
spec:
  generators:
    - list:
        elements:
          - name: jellyfin
          - name: cwa
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/msdeleyto/homelab-manifests.git
        targetRevision: main
        path: './media/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: media
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: baseline
            pod-security.kubernetes.io/enforce-version: latest
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/audit-version: latest
            istio.io/dataplane-mode: ambient
            istio.io/use-waypoint: cluster-waypoint
            istio.io/use-waypoint-namespace: network
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true